version: '3'

services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - 2181:2181
    networks:
      - java_kafka

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_CFG_LISTENERS=PLAINTEXT_LOCAL://:9092,PLAINTEXT_CONTAINER://:9093
      # - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT_LOCAL://127.0.0.1:9092,PLAINTEXT_CONTAINER://kafka:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT_LOCAL:PLAINTEXT,PLAINTEXT_CONTAINER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT_LOCAL
    networks:
      - java_kafka

  spring-boot-kafka:
    image: marsal/spring-boot-kafka
    container_name: spring-boot-kafka
    build: .
    networks:
      - java_kafka
    depends_on:
      - kafka
      - zookeeper
    ports:
      - 8010:8010
    environment:
      - BOOTSTRAP_SERVER=kafka:9093
      - PROFILE=prod

networks:
  java_kafka:
    name: java_kafka
    driver: bridge
